#!/bin/bash

# This hook copies dist files to gh-pages

SRC_BRANCH="master"
CURR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
STAGING="staging"

# Only update dist if pushing to master
if [ "$CURR_BRANCH" != "$SRC_BRANCH" ]; then
    exit 0
fi

LAST_COMMIT=$(git rev-parse $SRC_BRANCH)

gulp build --env=production
if [ ! -d "$STAGING" ]; then
    git clone -b gh-pages --single-branch $(git config --get remote.origin.url) $STAGING
fi
cd $STAGING
git pull
cp -r ../dist .
git add dist
git commit -m "Including changes from $SRC_BRANCH commit $LAST_COMMIT"
git push origin gh-pages
cd ..
